spring:
  application:
    name: eureka-server

server:
  port: 2001

---
spring:
  profiles: eureka1
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka1
  client:
    service-url:
      defaultZone: http://eureka2:2002/eureka
server:
  port: 2001

---
spring:
  profiles: eureka2
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka2
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka
server:
  port: 2002